// Catálogo de produtos. Edite aqui: preço, link de afiliado ("url") e categoria de cada item.
// Categorias válidas: batom, base, rimel, sombra, blush, pinceis, corretivo, primer
const PRODUCTS_DATA = [
  { "id": 1, "name": "Batom Líquido Matte Feels", "brand": "Ruby Rose", "category": "batom",
    "prices": { "mercadolivre": {"price": 15.90, "url": "https://mercadolivre.com.br/SEU-LINK-AFILIADO-AQUI"}, "amazon": {"price": 18.50, "url": "https://amazon.com.br/SEU-LINK-AFILIADO-AQUI"}, "shopee": {"price": 14.90, "url": "https://shopee.com.br/SEU-LINK-AFILIADO-AQUI"} } },
  { "id": 2, "name": "Batom Cremoso Cor & Cuidado", "brand": "Vult", "category": "batom",
    "prices": { "mercadolivre": {"price": 19.90, "url": "https://mercadolivre.com.br/SEU-LINK-AFILIADO-AQUI"}, "amazon": {"price": 21.90, "url": "https://amazon.com.br/SEU-LINK-AFILIADO-AQUI"}, "shopee": {"price": 20.50, "url": "https://shopee.com.br/SEU-LINK-AFILIADO-AQUI"} } },
  { "id": 3, "name": "Batom Duo Cor & Cuidado", "brand": "Eudora", "category": "batom",
    "prices": { "mercadolivre": {"price": 34.90, "url": "https://mercadolivre.com.br/SEU-LINK-AFILIADO-AQUI"}, "amazon": {"price": 36.90, "url": "https://amazon.com.br/SEU-LINK-AFILIADO-AQUI"}, "shopee": {"price": 32.90, "url": "https://shopee.com.br/SEU-LINK-AFILIADO-AQUI"} } },
  { "id": 4, "name": "Batom Líquido Matte", "brand": "Boca Rosa Beauty", "category": "batom",
    "prices": { "mercadolivre": {"price": 39.90, "url": "https://mercadolivre.com.br/SEU-LINK-AFILIADO-AQUI"}, "amazon": {"price": 42.90, "url": "https://amazon.com.br/SEU-LINK-AFILIADO-AQUI"}, "shopee": {"price": 37.90, "url": "https://shopee.com.br/SEU-LINK-AFILIADO-AQUI"} } },
  { "id": 5, "name": "Batom Ultra Color", "brand": "Avon", "category": "batom",
    "prices": { "mercadolivre": {"price": 24.90, "url": "https://mercadolivre.com.br/SEU-LINK-AFILIADO-AQUI"}, "amazon": {"price": 26.50, "url": "https://amazon.com.br/SEU-LINK-AFILIADO-AQUI"}, "shopee": {"price": 23.90, "url": "https://shopee.com.br/SEU-LINK-AFILIADO-AQUI"} } },

  { "id": 6, "name": "Base Líquida HD", "brand": "Vult", "category": "base",
    "prices": { "mercadolivre": {"price": 32.90, "url": "https://mercadolivre.com.br/SEU-LINK-AFILIADO-AQUI"}, "amazon": {"price": 35.90, "url": "https://amazon.com.br/SEU-LINK-AFILIADO-AQUI"}, "shopee": {"price": 31.50, "url": "https://shopee.com.br/SEU-LINK-AFILIADO-AQUI"} } },
  { "id": 7, "name": "Base Soft Blur", "brand": "Ruby Rose", "category": "base",
    "prices": { "mercadolivre": {"price": 24.90, "url": "https://mercadolivre.com.br/SEU-LINK-AFILIADO-AQUI"}, "amazon": {"price": 27.90, "url": "https://amazon.com.br/SEU-LINK-AFILIADO-AQUI"}, "shopee": {"price": 23.90, "url": "https://shopee.com.br/SEU-LINK-AFILIADO-AQUI"} } },
  { "id": 8, "name": "BT Skin Base Fluída", "brand": "Bruna Tavares", "category": "base",
    "prices": { "mercadolivre": {"price": 79.90, "url": "https://mercadolivre.com.br/SEU-LINK-AFILIADO-AQUI"}, "amazon": {"price": 84.90, "url": "https://amazon.com.br/SEU-LINK-AFILIADO-AQUI"}, "shopee": {"price": 76.90, "url": "https://shopee.com.br/SEU-LINK-AFILIADO-AQUI"} } },
  { "id": 9, "name": "Glam Fluído Base", "brand": "Eudora", "category": "base",
    "prices": { "mercadolivre": {"price": 54.90, "url": "https://mercadolivre.com.br/SEU-LINK-AFILIADO-AQUI"}, "amazon": {"price": 57.90, "url": "https://amazon.com.br/SEU-LINK-AFILIADO-AQUI"}, "shopee": {"price": 52.90, "url": "https://shopee.com.br/SEU-LINK-AFILIADO-AQUI"} } },
  { "id": 10, "name": "Base Facial Cor & Cuidado", "brand": "Payot", "category": "base",
    "prices": { "mercadolivre": {"price": 44.90, "url": "https://mercadolivre.com.br/SEU-LINK-AFILIADO-AQUI"}, "amazon": {"price": 47.90, "url": "https://amazon.com.br/SEU-LINK-AFILIADO-AQUI"}, "shopee": {"price": 43.50, "url": "https://shopee.com.br/SEU-LINK-AFILIADO-AQUI"} } },

  { "id": 11, "name": "Máscara Cílios Volume Extremo", "brand": "Ruby Rose", "category": "rimel",
    "prices": { "mercadolivre": {"price": 14.90, "url": "https://mercadolivre.com.br/SEU-LINK-AFILIADO-AQUI"}, "amazon": {"price": 16.90, "url": "https://amazon.com.br/SEU-LINK-AFILIADO-AQUI"}, "shopee": {"price": 13.90, "url": "https://shopee.com.br/SEU-LINK-AFILIADO-AQUI"} } },
  { "id": 12, "name": "Máscara Cílios Fatal", "brand": "Vult", "category": "rimel",
    "prices": { "mercadolivre": {"price": 18.90, "url": "https://mercadolivre.com.br/SEU-LINK-AFILIADO-AQUI"}, "amazon": {"price": 20.50, "url": "https://amazon.com.br/SEU-LINK-AFILIADO-AQUI"}, "shopee": {"price": 17.90, "url": "https://shopee.com.br/SEU-LINK-AFILIADO-AQUI"} } },
  { "id": 13, "name": "Máscara Volume Turbo", "brand": "Eudora", "category": "rimel",
    "prices": { "mercadolivre": {"price": 29.90, "url": "https://mercadolivre.com.br/SEU-LINK-AFILIADO-AQUI"}, "amazon": {"price": 31.90, "url": "https://amazon.com.br/SEU-LINK-AFILIADO-AQUI"}, "shopee": {"price": 28.50, "url": "https://shopee.com.br/SEU-LINK-AFILIADO-AQUI"} } },
  { "id": 14, "name": "Supershock Máscara", "brand": "Avon", "category": "rimel",
    "prices": { "mercadolivre": {"price": 22.90, "url": "https://mercadolivre.com.br/SEU-LINK-AFILIADO-AQUI"}, "amazon": {"price": 24.90, "url": "https://amazon.com.br/SEU-LINK-AFILIADO-AQUI"}, "shopee": {"price": 21.90, "url": "https://shopee.com.br/SEU-LINK-AFILIADO-AQUI"} } },
  { "id": 15, "name": "Máscara Efeito Fio a Fio", "brand": "Quem Disse Berenice", "category": "rimel",
    "prices": { "mercadolivre": {"price": 32.90, "url": "https://mercadolivre.com.br/SEU-LINK-AFILIADO-AQUI"}, "amazon": {"price": 34.90, "url": "https://amazon.com.br/SEU-LINK-AFILIADO-AQUI"}, "shopee": {"price": 31.90, "url": "https://shopee.com.br/SEU-LINK-AFILIADO-AQUI"} } },

  { "id": 16, "name": "Paleta de Sombras Chocolate", "brand": "Ruby Rose", "category": "sombra",
    "prices": { "mercadolivre": {"price": 29.90, "url": "https://mercadolivre.com.br/SEU-LINK-AFILIADO-AQUI"}, "amazon": {"price": 32.90, "url": "https://amazon.com.br/SEU-LINK-AFILIADO-AQUI"}, "shopee": {"price": 28.90, "url": "https://shopee.com.br/SEU-LINK-AFILIADO-AQUI"} } },
  { "id": 17, "name": "Paleta Nudes", "brand": "Vult", "category": "sombra",
    "prices": { "mercadolivre": {"price": 34.90, "url": "https://mercadolivre.com.br/SEU-LINK-AFILIADO-AQUI"}, "amazon": {"price": 37.90, "url": "https://amazon.com.br/SEU-LINK-AFILIADO-AQUI"}, "shopee": {"price": 33.50, "url": "https://shopee.com.br/SEU-LINK-AFILIADO-AQUI"} } },
  { "id": 18, "name": "Paleta Tons Terrosos", "brand": "Bruna Tavares", "category": "sombra",
    "prices": { "mercadolivre": {"price": 69.90, "url": "https://mercadolivre.com.br/SEU-LINK-AFILIADO-AQUI"}, "amazon": {"price": 74.90, "url": "https://amazon.com.br/SEU-LINK-AFILIADO-AQUI"}, "shopee": {"price": 67.90, "url": "https://shopee.com.br/SEU-LINK-AFILIADO-AQUI"} } },
  { "id": 19, "name": "Paleta de Sombras Matte", "brand": "Dailus", "category": "sombra",
    "prices": { "mercadolivre": {"price": 27.90, "url": "https://mercadolivre.com.br/SEU-LINK-AFILIADO-AQUI"}, "amazon": {"price": 29.90, "url": "https://amazon.com.br/SEU-LINK-AFILIADO-AQUI"}, "shopee": {"price": 26.90, "url": "https://shopee.com.br/SEU-LINK-AFILIADO-AQUI"} } },
  { "id": 20, "name": "Paleta Glam Colors", "brand": "Eudora", "category": "sombra",
    "prices": { "mercadolivre": {"price": 44.90, "url": "https://mercadolivre.com.br/SEU-LINK-AFILIADO-AQUI"}, "amazon": {"price": 47.90, "url": "https://amazon.com.br/SEU-LINK-AFILIADO-AQUI"}, "shopee": {"price": 43.90, "url": "https://shopee.com.br/SEU-LINK-AFILIADO-AQUI"} } },

  { "id": 21, "name": "Blush Compacto", "brand": "Ruby Rose", "category": "blush",
    "prices": { "mercadolivre": {"price": 12.90, "url": "https://mercadolivre.com.br/SEU-LINK-AFILIADO-AQUI"}, "amazon": {"price": 14.50, "url": "https://amazon.com.br/SEU-LINK-AFILIADO-AQUI"}, "shopee": {"price": 11.90, "url": "https://shopee.com.br/SEU-LINK-AFILIADO-AQUI"} } },
  { "id": 22, "name": "Iluminador em Pó", "brand": "Vult", "category": "blush",
    "prices": { "mercadolivre": {"price": 22.90, "url": "https://mercadolivre.com.br/SEU-LINK-AFILIADO-AQUI"}, "amazon": {"price": 24.90, "url": "https://amazon.com.br/SEU-LINK-AFILIADO-AQUI"}, "shopee": {"price": 21.90, "url": "https://shopee.com.br/SEU-LINK-AFILIADO-AQUI"} } },
  { "id": 23, "name": "Blush Cor & Cuidado", "brand": "Payot", "category": "blush",
    "prices": { "mercadolivre": {"price": 27.90, "url": "https://mercadolivre.com.br/SEU-LINK-AFILIADO-AQUI"}, "amazon": {"price": 29.90, "url": "https://amazon.com.br/SEU-LINK-AFILIADO-AQUI"}, "shopee": {"price": 26.50, "url": "https://shopee.com.br/SEU-LINK-AFILIADO-AQUI"} } },
  { "id": 24, "name": "Iluminador Facial", "brand": "Boca Rosa Beauty", "category": "blush",
    "prices": { "mercadolivre": {"price": 39.90, "url": "https://mercadolivre.com.br/SEU-LINK-AFILIADO-AQUI"}, "amazon": {"price": 42.90, "url": "https://amazon.com.br/SEU-LINK-AFILIADO-AQUI"}, "shopee": {"price": 38.50, "url": "https://shopee.com.br/SEU-LINK-AFILIADO-AQUI"} } },
  { "id": 25, "name": "Blush Duo", "brand": "Avon", "category": "blush",
    "prices": { "mercadolivre": {"price": 19.90, "url": "https://mercadolivre.com.br/SEU-LINK-AFILIADO-AQUI"}, "amazon": {"price": 21.90, "url": "https://amazon.com.br/SEU-LINK-AFILIADO-AQUI"}, "shopee": {"price": 18.90, "url": "https://shopee.com.br/SEU-LINK-AFILIADO-AQUI"} } },

  { "id": 26, "name": "Kit Pincéis Maquiagem 12 peças", "brand": "Macrilan", "category": "pinceis",
    "prices": { "mercadolivre": {"price": 45.90, "url": "https://mercadolivre.com.br/SEU-LINK-AFILIADO-AQUI"}, "amazon": {"price": 49.90, "url": "https://amazon.com.br/SEU-LINK-AFILIADO-AQUI"}, "shopee": {"price": 42.90, "url": "https://shopee.com.br/SEU-LINK-AFILIADO-AQUI"} } },
  { "id": 27, "name": "Esponja de Maquiagem Premium", "brand": "Genérica", "category": "pinceis",
    "prices": { "mercadolivre": {"price": 14.90, "url": "https://mercadolivre.com.br/SEU-LINK-AFILIADO-AQUI"}, "amazon": {"price": 16.90, "url": "https://amazon.com.br/SEU-LINK-AFILIADO-AQUI"}, "shopee": {"price": 12.90, "url": "https://shopee.com.br/SEU-LINK-AFILIADO-AQUI"} } },
  { "id": 28, "name": "Kit Pincéis Basic", "brand": "Ruby Rose", "category": "pinceis",
    "prices": { "mercadolivre": {"price": 29.90, "url": "https://mercadolivre.com.br/SEU-LINK-AFILIADO-AQUI"}, "amazon": {"price": 32.90, "url": "https://amazon.com.br/SEU-LINK-AFILIADO-AQUI"}, "shopee": {"price": 27.90, "url": "https://shopee.com.br/SEU-LINK-AFILIADO-AQUI"} } },
  { "id": 29, "name": "Pincel Kabuki", "brand": "Vult", "category": "pinceis",
    "prices": { "mercadolivre": {"price": 16.90, "url": "https://mercadolivre.com.br/SEU-LINK-AFILIADO-AQUI"}, "amazon": {"price": 18.90, "url": "https://amazon.com.br/SEU-LINK-AFILIADO-AQUI"}, "shopee": {"price": 15.50, "url": "https://shopee.com.br/SEU-LINK-AFILIADO-AQUI"} } },
  { "id": 30, "name": "Kit Esponjas Maquiagem 3un", "brand": "Genérica", "category": "pinceis",
    "prices": { "mercadolivre": {"price": 9.90, "url": "https://mercadolivre.com.br/SEU-LINK-AFILIADO-AQUI"}, "amazon": {"price": 11.90, "url": "https://amazon.com.br/SEU-LINK-AFILIADO-AQUI"}, "shopee": {"price": 8.90, "url": "https://shopee.com.br/SEU-LINK-AFILIADO-AQUI"} } },

  { "id": 31, "name": "Corretivo Líquido", "brand": "Ruby Rose", "category": "corretivo",
    "prices": { "mercadolivre": {"price": 14.90, "url": "https://mercadolivre.com.br/SEU-LINK-AFILIADO-AQUI"}, "amazon": {"price": 16.90, "url": "https://amazon.com.br/SEU-LINK-AFILIADO-AQUI"}, "shopee": {"price": 13.90, "url": "https://shopee.com.br/SEU-LINK-AFILIADO-AQUI"} } },
  { "id": 32, "name": "Corretivo Alta Cobertura", "brand": "Vult", "category": "corretivo",
    "prices": { "mercadolivre": {"price": 19.90, "url": "https://mercadolivre.com.br/SEU-LINK-AFILIADO-AQUI"}, "amazon": {"price": 21.90, "url": "https://amazon.com.br/SEU-LINK-AFILIADO-AQUI"}, "shopee": {"price": 18.50, "url": "https://shopee.com.br/SEU-LINK-AFILIADO-AQUI"} } },
  { "id": 33, "name": "BT Skin Corretivo", "brand": "Bruna Tavares", "category": "corretivo",
    "prices": { "mercadolivre": {"price": 44.90, "url": "https://mercadolivre.com.br/SEU-LINK-AFILIADO-AQUI"}, "amazon": {"price": 47.90, "url": "https://amazon.com.br/SEU-LINK-AFILIADO-AQUI"}, "shopee": {"price": 42.90, "url": "https://shopee.com.br/SEU-LINK-AFILIADO-AQUI"} } },
  { "id": 34, "name": "Corretivo Glam", "brand": "Eudora", "category": "corretivo",
    "prices": { "mercadolivre": {"price": 32.90, "url": "https://mercadolivre.com.br/SEU-LINK-AFILIADO-AQUI"}, "amazon": {"price": 34.90, "url": "https://amazon.com.br/SEU-LINK-AFILIADO-AQUI"}, "shopee": {"price": 31.50, "url": "https://shopee.com.br/SEU-LINK-AFILIADO-AQUI"} } },
  { "id": 35, "name": "Corretivo Facial", "brand": "Payot", "category": "corretivo",
    "prices": { "mercadolivre": {"price": 27.90, "url": "https://mercadolivre.com.br/SEU-LINK-AFILIADO-AQUI"}, "amazon": {"price": 29.90, "url": "https://amazon.com.br/SEU-LINK-AFILIADO-AQUI"}, "shopee": {"price": 26.90, "url": "https://shopee.com.br/SEU-LINK-AFILIADO-AQUI"} } },

  { "id": 36, "name": "Primer Facial", "brand": "Vult", "category": "primer",
    "prices": { "mercadolivre": {"price": 29.90, "url": "https://mercadolivre.com.br/SEU-LINK-AFILIADO-AQUI"}, "amazon": {"price": 32.90, "url": "https://amazon.com.br/SEU-LINK-AFILIADO-AQUI"}, "shopee": {"price": 28.50, "url": "https://shopee.com.br/SEU-LINK-AFILIADO-AQUI"} } },
  { "id": 37, "name": "Água Fixadora de Maquiagem", "brand": "Ruby Rose", "category": "primer",
    "prices": { "mercadolivre": {"price": 19.90, "url": "https://mercadolivre.com.br/SEU-LINK-AFILIADO-AQUI"}, "amazon": {"price": 21.90, "url": "https://amazon.com.br/SEU-LINK-AFILIADO-AQUI"}, "shopee": {"price": 18.90, "url": "https://shopee.com.br/SEU-LINK-AFILIADO-AQUI"} } },
  { "id": 38, "name": "Primer Glam", "brand": "Eudora", "category": "primer",
    "prices": { "mercadolivre": {"price": 34.90, "url": "https://mercadolivre.com.br/SEU-LINK-AFILIADO-AQUI"}, "amazon": {"price": 37.90, "url": "https://amazon.com.br/SEU-LINK-AFILIADO-AQUI"}, "shopee": {"price": 33.50, "url": "https://shopee.com.br/SEU-LINK-AFILIADO-AQUI"} } },
  { "id": 39, "name": "Água Micelar", "brand": "Payot", "category": "primer",
    "prices": { "mercadolivre": {"price": 24.90, "url": "https://mercadolivre.com.br/SEU-LINK-AFILIADO-AQUI"}, "amazon": {"price": 26.90, "url": "https://amazon.com.br/SEU-LINK-AFILIADO-AQUI"}, "shopee": {"price": 23.90, "url": "https://shopee.com.br/SEU-LINK-AFILIADO-AQUI"} } },
  { "id": 40, "name": "Primer Efeito Blur", "brand": "Avon", "category": "primer",
    "prices": { "mercadolivre": {"price": 22.90, "url": "https://mercadolivre.com.br/SEU-LINK-AFILIADO-AQUI"}, "amazon": {"price": 24.90, "url": "https://amazon.com.br/SEU-LINK-AFILIADO-AQUI"}, "shopee": {"price": 21.90, "url": "https://shopee.com.br/SEU-LINK-AFILIADO-AQUI"} } },

  // Produto real, com link de afiliado e foto de verdade (puxados do Mercado Livre)
  { "id": 41, "name": "Batom Líquido Feels Mood Ruby Rose Cor 13", "brand": "Ruby Rose", "category": "batom",
    "image": "foto-batom-ruby-rose-mood-13.png",
    "prices": { "mercadolivre": {"price": 19.90, "url": "https://meli.la/1FETtp2"} } }
];
